name: clean_architecture_base
description: Clean Architecture module base to be used in different modules
# version: 1.0.0
# homepage: https://www.example.com
# author: salmaahhmed <salmaahhmed2@yahoo.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  get_it: ^3.1.0
  rxdart: ^0.23.1
  logging: ^0.11.4
  equatable: ^1.0.3 
  bloc: ^3.0.0
  sealed_unions: ^3.0.2+2
